PerfumeShop/PerfumeShop.Web/Areas/Shop/Controllers/BasketController.cs
namespace PerfumeShop.Web.Areas.Shop.Controllers;

[Area("Shop")]
public class BasketController : Controller
{
    private readonly IBasketService _basketService;
    private readonly IBasketViewModelService _basketViewModelService;
    private readonly ICheckoutService _checkoutService;
	private readonly IBasketQueryService _basketQueryService;
	private readonly IBasketItemQueryService _basketItemQueryService;
	private readonly IProductQueryService _productQueryService;


	public BasketController(
        IBasketService basketService,
        IBasketViewModelService basketViewModelService,
		ICheckoutService checkoutService,
		IBasketQueryService basketQueryService,
		IBasketItemQueryService basketItemQueryService,
		IProductQueryService productQueryService)
    {
        _basketService = basketService;
        _basketViewModelService = basketViewModelService;
        _checkoutService = checkoutService;
		_basketQueryService = basketQueryService;
		_basketItemQueryService = basketItemQueryService;
        _productQueryService = productQueryService;
	}

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var basket = await _basketViewModelService.GetBasketForUserAsync(GetBuyerId());
        return View(basket);
    }

    [HttpPost]
    public async Task<IActionResult> AddToBasket(int productId, int quantity = 1)
    {
        var userName = GetBuyerId();
		var inBasketQty = await _basketQueryService.GetProductQtyAsync(userName, productId);

		var availability = await _checkoutService.AvailabilityStockAsync(productId, quantity + inBasketQty);
        if (availability.IsAvailable)
        {
            await _basketService.AddItemToBasketAsync(userName, productId, quantity);

            HttpContext.Session.Set(Constants.BASKET_ITEMS_QTY,
                quantity + HttpContext.Session.GetInt32(Constants.BASKET_ITEMS_QTY));

            TempData["success"] = $"Product \"{availability.ProductName}\"" +
                $" added to cart in quantity {quantity}.";
        }
        else
        {
            TempData["error"] = $"Product \"{availability.ProductName}\"" +
                $" already added to cart in quantity {availability.DesiredQty - quantity}." +
                $" You can add no more than {availability.StockQty}.";
        }
        return Redirect(Request.GetTypedHeaders().Referer.ToString());
    }

	[HttpPost]
	public async Task<IActionResult> UpdateItemBasket(int basketItemId, int quantity)
    {
        var productId = await _basketItemQueryService.GetProductIdAsync(basketItemId);
		var inBasketQty = await _basketQueryService.GetProductQtyAsync(GetBuyerId(), productId);
		var availability = await _checkoutService.AvailabilityStockAsync(productId, quantity);

        if (availability.IsAvailable) 
        {          
            if (quantity > 0 && quantity != inBasketQty)
            {
                var basketItem = await _basketService.UpdateItemBasketAsync(basketItemId, quantity);

                HttpContext.Session.Set(Constants.BASKET_ITEMS_QTY, quantity);

                TempData["success"] = $"Set new quantity \"{availability.DesiredQty}\"" +
					$" for product \"{availability.ProductName}\".";
			}
            else
            {
				TempData["info"] = $"The new quantity must not be equal to the" +
                    $" current quantity and must be greater than zero.";
			}
		}
        else
        {
			TempData["error"] = $"Product \"{availability.ProductName}\"" +
	            $" already added to cart in quantity {availability.DesiredQty - quantity}." +
	            $" You can add no more than {availability.StockQty}.";
		}
        return RedirectToAction(nameof(Index));
	}

	[HttpPost]
	public async Task<IActionResult> DeleteItemBasket(int basketItemId)
    {
        var basketItem = await _basketService.DeleteItemFromBasketAsync(basketItemId);
        var productName = await _productQueryService.GetProductNameAsync(basketItem.ProductId);

        HttpContext.Session.Set(Constants.BASKET_ITEMS_QTY,
            HttpContext.Session.GetInt32(Constants.BASKET_ITEMS_QTY) - basketItem.Quantity);

        TempData["success"] = $"Position with product \"{productName}\" has been deleted.";

        return RedirectToAction(nameof(Index));
	}

	[HttpPost]
	public async Task<IActionResult> ClearBasket(int basketId)
    {
		await _basketService.ClearBasketAsync(basketId);

        HttpContext.Session.Set(Constants.BASKET_ITEMS_QTY, 0);

        TempData["success"] = $"Your basket has been cleared.";

		return RedirectToAction(nameof(Index));
	}

	private string GetBuyerId()
    {
        string? userName = null;

        if (Request.HttpContext.User.Identity.IsAuthenticated)
        {
            return Request.HttpContext.User.Identity.Name;
        }
        if (Request.Cookies.ContainsKey(Constants.BASKET_COOKIE))
        {
            userName = Request.Cookies[Constants.BASKET_COOKIE];

            if (!Request.HttpContext.User.Identity.IsAuthenticated 
                && !Guid.TryParse(userName, out var _))
            {
                userName = null;                
            }
        }
        if (userName != null) return userName;

        userName = Guid.NewGuid().ToString();

        Response.Cookies.Append(Constants.BASKET_COOKIE, userName,
            new CookieOptions 
            {
                IsEssential = true,
                Expires = DateTime.Today.AddYears(1)
            });

        return userName;
    }
}

PerfumeShop/PerfumeShop.Web/Areas/Shop/Controllers/HomeController.cs
namespace PerfumeShop.Web.Areas.User.Controllers;

[Area("Shop")]
[AllowAnonymous]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly ICatalogViewModelService _catalogViewModelService;

    public HomeController(
        ILogger<HomeController> logger,
        ICatalogViewModelService catalogViewModelService)
    {
        _logger = logger;
        _catalogViewModelService = catalogViewModelService;
    }

    public async Task<IActionResult> Index()
    {
        var productsView = await _catalogViewModelService.GetAllDiscountedProducts(onlyAvailable: true);

        return View(productsView);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        _logger.LogError("Error");
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

PerfumeShop/PerfumeShop.Web/Areas/Shop/Controllers/OrderController.cs
namespace PerfumeShop.Web.Areas.Shop.Controllers;

[Area("Shop")]
[Authorize]
public class OrderController : Controller
{
    private readonly IMapper _mapper;
	private readonly IBasketViewModelService _basketViewModelService;
	private readonly IOrderViewModelService _orderViewModelService;
    private readonly IOrderService _orderService;
	private readonly IPhysicalShopQueryService _physicalShopQueryService;
	private readonly ICatalogProductService _catalogProductService;
	private readonly IBasketService _basketService;
	private readonly SignInManager<AppUser> _signInManager;
	private readonly UserManager<AppUser> _userManager;


	public OrderController(
		IMapper mapper,
		IBasketViewModelService basketViewModelService,
		IOrderService orderService,
		IOrderViewModelService orderViewModelService,
        IPhysicalShopQueryService physicalShopQueryService,
		ICatalogProductService catalogProductService,
		IBasketService basketService,
		SignInManager<AppUser> signInManager,
		UserManager<AppUser> userManager)
    {
		_mapper = mapper;
		_basketViewModelService = basketViewModelService;
		_orderService = orderService;
		_orderViewModelService = orderViewModelService;
		_physicalShopQueryService = physicalShopQueryService;
		_catalogProductService = catalogProductService;
		_basketService = basketService;
		_signInManager = signInManager;
		_userManager = userManager;
	}

    [HttpGet]
    public async Task<IActionResult> Index()
    {
		OrderCreateViewModel order = _signInManager.IsSignedIn(HttpContext.User)
			? await _orderViewModelService.GetOrderCreateModelForAuthorizedUserAsync(User.Identity.Name)
			: await _orderViewModelService.GetOrderCreateModelForAnonymousUserAsync(GetAnonymousUserId());

		return View(order);			
    }

    [HttpPost]
    public async Task<IActionResult> OrderByPickup(OrderCreateViewModel model)
    {
		ModelState.Remove(nameof(model.Address));

        if (ModelState.IsValid)
        {
			var deliveryAddress = await _physicalShopQueryService.GetAddressAsync(model.PickupPointId);
            var customer = _mapper.Map<Customer>(model.Buyer);
            var paymentMethod = (PaymentMethods)model.PaymentMethodId;

            var order = await _orderService.CreateOrderAsync(
                paymentMethod,
                DeliveryMethods.Pickup,
                deliveryAddress,
                customer,
                model.Basket.Id);

            SaveTrackingIdToSession(order.TrackingId);

            return RedirectToPage(GetRedirectionPageName(paymentMethod));
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> OrderByCourier(OrderCreateViewModel model)
    {
        if (ModelState.IsValid)
		{
			var deliveryAddress = _mapper.Map<Address>(model.Address);
			var customer = _mapper.Map<Customer>(model.Buyer);
			var paymentMethod = (PaymentMethods)model.PaymentMethodId;

			var order = await _orderService.CreateOrderAsync(
                paymentMethod,
				DeliveryMethods.Courier,
				deliveryAddress,
				customer,
				model.Basket.Id);

			SaveTrackingIdToSession(order.TrackingId);

            return RedirectToPage(GetRedirectionPageName(paymentMethod));
		}

        return RedirectToAction(nameof(Index));
    }

	private void SaveTrackingIdToSession(string trackingId)
	{
        if (HttpContext.Session.Keys.Contains(Constants.SESSION_ORDER_TRACKING_ID))
        {
            HttpContext.Session.Remove(Constants.SESSION_ORDER_TRACKING_ID);
        }
        HttpContext.Session.Set<String>(Constants.SESSION_ORDER_TRACKING_ID, trackingId);
    }

	private string GetRedirectionPageName(PaymentMethods method) => method switch
	{
		PaymentMethods.Cash => "/OrderSuccess",
		PaymentMethods.PaymentCard => "/Payment",
		_ => throw new ArgumentOutOfRangeException(nameof(method), $"Not expected direction value: {method}"),
    };

    private string GetAnonymousUserId()
	{
		if (Request.Cookies.ContainsKey(Constants.BASKET_COOKIE))
		{
			return Request.Cookies[Constants.BASKET_COOKIE];
		}
		else
		{
			var userName = Guid.NewGuid().ToString();
			Response.Cookies.Append(Constants.BASKET_COOKIE, userName,
			new CookieOptions
			{
				IsEssential = true,
				Expires = DateTime.Today.AddYears(1)
			});

			return userName;
		}
	}
}

PerfumeShop/PerfumeShop.Web/Areas/Shop/Pages/Catalog.cshtml.cs
namespace PerfumeShop.Web.Areas.Shop.Pages;

[Area("Shop")]
public class CatalogModel : PageModel
{
    public CatalogIndexViewModel CatalogIndex { get; set; } = new();
    private readonly ICatalogViewModelService _catalogService;

    public CatalogModel(ICatalogViewModelService catalogService)
    {
        _catalogService = catalogService;
    }


    public async Task OnGetAsync(CatalogIndexViewModel catalogIndex, PagedInfoViewModel pagedInfo)
    {        
        catalogIndex.MaxPrice = await _catalogService.DefineMaxPrice(catalogIndex.MaxPrice);

        var pagedList = await _catalogService.GetCatalogPagedListAsync(
                onlyDiscount: catalogIndex.OnlyDiscount,
                minPrice: catalogIndex.MinPrice,
                maxPrice: catalogIndex.MaxPrice,
                brandId: catalogIndex.BrandId,
                genderId: catalogIndex.GenderId,
                aromaTypeId: catalogIndex.AromaTypeId,
                releaseFormId: catalogIndex.ReleaseFormId,
                pageIndex: pagedInfo.PageIndex,
                itemsPerPage: pagedInfo.ItemsPerPage == default
                    ? (int)ItemsPerPage.Ten
                    : pagedInfo.ItemsPerPage);

        CatalogIndex = await _catalogService.GetCatalogIndexAsync(
            pagedList, catalogIndex.MinPrice, catalogIndex.MaxPrice, catalogIndex.OnlyDiscount);
    }
}

PerfumeShop/PerfumeShop.Web/Areas/Shop/Pages/OrderSuccess.cshtml.cs
using Microsoft.IdentityModel.Tokens;
namespace PerfumeShop.Web.Areas.Shop.Pages;

[Area("Shop")]
[Authorize]
public class OrderSuccessModel : PageModel
{
    private readonly IOrderQueryService _orderQueryService;
    private readonly IBasketQueryService _basketQueryService;
    private readonly IOrderViewModelService _orderViewModelService;
    private readonly IEmailService _emailService;
    private readonly ICatalogProductService _catalogProductService;
    private readonly IBasketService _basketService;
    private readonly UserManager<AppUser> _userManager;
    private readonly SignInManager<AppUser> _signInManager;

	public OrderSuccessModel(
        IOrderQueryService orderQueryService,
        IOrderViewModelService orderViewModelService,
        IEmailService emailService,
        IBasketService basketService,
        ICatalogProductService catalogProductService,
        UserManager<AppUser> userManager,
        SignInManager<AppUser> signInManager,
        IBasketQueryService basketQueryService)
    {
        _orderQueryService = orderQueryService;
        _orderViewModelService = orderViewModelService;
        _basketService = basketService;
        _catalogProductService = catalogProductService;
        _emailService = emailService;
        _userManager = userManager;
        _signInManager = signInManager;
        _basketQueryService = basketQueryService;

    }

    public string EmailModel { get; set; } = new string(string.Empty);
    public string OrderTrackingId { get; set; } = new string(string.Empty);


    public async Task OnGetAsync()
    {
        if (_signInManager.IsSignedIn(HttpContext.User))
        {           
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            EmailModel = user.Email;

            if (HttpContext.Session.Keys.Contains(Constants.SESSION_ORDER_TRACKING_ID))
            {
                OrderTrackingId = HttpContext.Session.Get<String>(Constants.SESSION_ORDER_TRACKING_ID)!;

                var orderId = await _orderQueryService.GetOrderIdAsync(OrderTrackingId);
                var basketId = await _basketQueryService.GetBasketIdAsync(User.Identity.Name);
                var orderitems = await _orderQueryService.GetOrderItemsAsync(orderId);

                await _catalogProductService.UpdateStockAfterOrderAsync(orderitems);
                await _basketService.ClearBasketAsync(basketId);
                HttpContext.Session.Remove(Constants.BASKET_ITEMS_QTY);
                await SendOrderToEmailAsync(OrderTrackingId);
            }         
        }           
    }

    public async Task<IActionResult> OnPostOrderIdAsync(string trackingId)
    {
        if (trackingId.IsNullOrEmpty())
        {
            return Page();
        }
        else
        {
            var orderId = await _orderQueryService.GetOrderIdAsync(trackingId);
            return Redirect($"/OrderHistory/Details?id={orderId}");
        }
    }

    private async Task<bool> SendOrderToEmailAsync(string trackingId)
    {
        var orderId = await _orderQueryService.GetOrderIdAsync(trackingId);
        var orderEmail = await _orderViewModelService.GetOrderEmailViewModelAsync(orderId);

        return await _emailService.SendEmailOrderAsync(orderEmail);
    }
}

PerfumeShop/PerfumeShop.Web/Areas/Shop/Pages/ProductDetails.cshtml.cs
namespace PerfumeShop.Web.Areas.Shop.Pages;

[Area("Shop")]
[AllowAnonymous]
public class ProductDetailsModel : PageModel
{
    public ProductViewModel Product { get; set; } = new();
    private readonly IViewModelService<CatalogProduct, ProductViewModel, CatalogDbContext> _viewModelService;

    public ProductDetailsModel(IViewModelService<CatalogProduct, ProductViewModel, CatalogDbContext> viewModelService)
    {
        _viewModelService = viewModelService;
    }

    public async Task OnGet(int id)
    {
        Product = await _viewModelService.GetViewModelByIdAsync(id);
    }
}

PerfumeShop/PerfumeShop.Web/Areas/Shop/Pages/OrderSuccess.cshtml
@page
@model OrderSuccessModel
@{
    ViewData["Title"] = "Order Success";
}

<body>
    <div class="vh-100 d-flex justify-content-center">
        <div>
            <div class="mb-4 text-center">
                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="130" height="130" viewBox="0 0 100 100">
                    <path fill="#e6edb7" d="M50 13A37 37 0 1 0 50 87A37 37 0 1 0 50 13Z"></path>
                    <path fill="#88ae45" d="M13 27A2 2 0 1 0 13 31A2 2 0 1 0 13 27Z"></path>
                    <path fill="#f1bc19" d="M77 12A1 1 0 1 0 77 14 1 1 0 1 0 77 12zM83 11A4 4 0 1 0 83 19 4 4 0 1 0 83 11z"></path>
                    <path fill="#88ae45" d="M87 22A2 2 0 1 0 87 26A2 2 0 1 0 87 22Z"></path>
                    <path fill="#fbcd59" d="M81 74A2 2 0 1 0 81 78 2 2 0 1 0 81 74zM15 59A4 4 0 1 0 15 67 4 4 0 1 0 15 59z"></path>
                    <path fill="#88ae45" d="M25 85A2 2 0 1 0 25 89A2 2 0 1 0 25 85Z"></path>
                    <path fill="#fff" d="M18.5 51A2.5 2.5 0 1 0 18.5 56A2.5 2.5 0 1 0 18.5 51Z"></path>
                    <path fill="#f1bc19" d="M21 66A1 1 0 1 0 21 68A1 1 0 1 0 21 66Z"></path>
                    <path fill="#fff" d="M80 33A1 1 0 1 0 80 35A1 1 0 1 0 80 33Z"></path>
                    <g><path fill="#88ae45" d="M50 26.042A23.958 23.958 0 1 0 50 73.958A23.958 23.958 0 1 0 50 26.042Z"></path><path fill="#472b29" d="M50,26.4c13.013,0,23.6,10.587,23.6,23.6S63.013,73.6,50,73.6S26.4,63.013,26.4,50 S36.987,26.4,50,26.4 M50,25c-13.807,0-25,11.193-25,25s11.193,25,25,25s25-11.193,25-25S63.807,25,50,25L50,25z"></path><path fill="#fdfcef" d="M50 30.5A19.5 19.5 0 1 0 50 69.5A19.5 19.5 0 1 0 50 30.5Z"></path><path fill="#472b29" d="M69.762,46.954c-0.043-0.273-0.298-0.46-0.571-0.418c-0.273,0.042-0.461,0.297-0.417,0.571 c0.931,5.976-1.054,12.082-5.309,16.334c-7.417,7.412-19.485,7.412-26.902,0c-7.417-7.411-7.417-19.471,0-26.883 c7.417-7.411,19.485-7.411,26.902,0c0.778,0.778,1.493,1.642,2.186,2.641c0.158,0.227,0.469,0.284,0.697,0.126 c0.225-0.155,0.283-0.468,0.126-0.696c-0.728-1.049-1.481-1.958-2.302-2.778c-7.807-7.801-20.51-7.802-28.318,0 c-7.807,7.802-7.807,20.496,0,28.298c7.807,7.801,20.51,7.802,28.318,0C68.653,59.672,70.743,53.244,69.762,46.954z"></path><path fill="#472b29" d="M67.569,42.796c0.105,0.256,0.398,0.378,0.653,0.273c0.254-0.104,0.378-0.396,0.272-0.652 c-0.315-0.766-0.609-1.395-0.926-1.977c-0.132-0.243-0.436-0.332-0.679-0.2c-0.043,0.023-0.082,0.053-0.115,0.086 c-0.153,0.153-0.194,0.393-0.086,0.593C66.989,41.468,67.269,42.065,67.569,42.796z"></path></g>
                    <g><path fill="#88ae45" d="M41,48.375c-0.434,0-0.842,0.169-1.149,0.476c-0.307,0.307-0.476,0.715-0.476,1.149 s0.169,0.842,0.476,1.149l7,7c0.307,0.307,0.715,0.476,1.149,0.476V59l0.031-0.375c0.445-0.009,0.869-0.201,1.167-0.526l11-12 c0.293-0.32,0.444-0.735,0.426-1.169c-0.019-0.434-0.206-0.833-0.525-1.127c-0.321-0.293-0.728-0.45-1.169-0.426 c-0.433,0.019-0.833,0.205-1.126,0.525l-9.854,10.749l-5.8-5.8C41.842,48.544,41.434,48.375,41,48.375z"></path><path fill="#472b29" d="M59,43.75L59,43.75c0.313,0,0.613,0.117,0.845,0.329c0.246,0.226,0.389,0.533,0.404,0.867 c0.014,0.334-0.102,0.653-0.328,0.899l-11,12c-0.229,0.25-0.555,0.398-0.921,0.405c-0.334,0-0.648-0.13-0.884-0.366l-7-7 C39.88,50.648,39.75,50.334,39.75,50s0.13-0.648,0.367-0.884C40.352,48.88,40.666,48.75,41,48.75s0.648,0.13,0.884,0.366 l5.523,5.523l0.554,0.554l0.529-0.577l9.589-10.461C58.318,43.894,58.645,43.75,59,43.75 M59,43c-0.541,0-1.08,0.218-1.474,0.649 l-9.589,10.46l-5.523-5.523C42.024,48.195,41.512,48,41,48s-1.024,0.195-1.414,0.586c-0.781,0.781-0.781,2.047,0,2.828l7,7 C46.961,58.79,47.47,59,48,59c0.015,0,0.029,0,0.043,0c0.545-0.012,1.062-0.246,1.431-0.648l11-12 c0.747-0.814,0.691-2.08-0.123-2.826C59.967,43.174,59.483,43,59,43L59,43z"></path></g>
                </svg>
            </div>
            <div class="text-center">
                <h1>Thanks for your Order !</h1>
                <h4>
                    <span class="text-muted">You order number is @Model.OrderTrackingId</span>
                </h4>
                <p class="p-4">
                    We have sent a cash voucher to your email:
                    <a href="mailto:@Model.EmailModel">@Model.EmailModel</a>
                </p> 

                <div class="d-inline-flex gap-2 mb-5">
                    <form asp-page-handler="OrderId" asp-route-trackingId="@Model.OrderTrackingId" method="post">
                        <button class="btn btn-primary">Order Details</button>
                    </form>

                    <a asp-area="Shop" asp-page="/Catalog" class="btn btn-primary">Continue Shopping...</a>
                </div>               
            </div>
        </div>
    </div>
</body>

PerfumeShop/PerfumeShop.Web/Areas/Shop/Pages/ProductDetails.cshtml
@page
@model ProductDetailsModel

<form method="post" asp-area="Shop" asp-controller="Basket" asp-action="AddToBasket" asp-route-productId="@Model.Product.Id">
    <div class="row py-5">
        <div class="col-7">
            <div class="container text-center">
                <img src="@Constants.CATALOG_IMAGE_PATH@Model.Product.PictureUri" class="img-thumbnail shadow-sm" style="max-width:60%" alt="...">
            </div>
        </div>
        <div class="col-5">
            @if(Model.Product.Stock > 0)
            {
                if (Model.Product.DiscountPrice is not null)
                {
                    <img src="@Constants.SALE_IMAGE" class="float-end" style="max-inline-size:25%">
                }               
            }
            else
            {
                <img src="@Constants.SOLD_OUT_IMAGE" class="float-end" style="max-width:25%">
            }

            <div class="fs-3 fw-semibold">@Model.Product.Brand.Name</div>
            <div class="fs-3 fw-normal text-muted">@Model.Product.Name</div>
            <hr class="my-3">
            <div class="py-4 fs-6">
                <p><b>Volume: </b>@Model.Product.Volume ml.</p>
                <p><b>Gender: </b>@Model.Product.Gender.Name</p>
                <p><b>Aroma Type: </b>@Model.Product.AromaType.Name</p>
            </div>
            @if (Model.Product.Stock > 0)
            {
                if (Model.Product.DiscountPrice is not null)
                {
                    <div class="fs-6">
                        <b>Old Price: </b>@Model.Product.Price.ToString("c")
                    </div>
                    <div class="fs-4">
                        <p class="fs-4"><b>Price: </b>@Model.Product.DiscountPrice?.ToString("c")</p>
                    </div>
                }
                else
                {
                    <p class="fs-4"><b>Price: </b>@Model.Product.Price.ToString("c")</p>                   
                }
                <div class="py-0">
                    <div class="col-3">
                        <span class="text-muted">Available: @Model.Product.Stock</span>
                        <div class="input-group input-group-sm mb-3">
                            <span class="input-group-text text-bg-dark">qty.</span>
                            <input type="number" min="1" max="@Model.Product.Stock"
                                   step="1" value="1" name="quantity" class="form-control shadow-none">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark rounded-pill px-3 mb-3">
                        <span class="">Add To Basket</span>
                    </button>
                </div>
            }
            else
            {
                <img src="@Constants.NOT_AVAILABLE_IMAGE" style="max-width:30%">
            }              
            <div class="accordion py-4">
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Description
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show">
                        <div class="accordion-body">
                            <p class="fs-5 fw-light">@Html.Raw(Model.Product.Description)</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>