PerfumeShop/PerfumeShop.Web/Areas/Admin/Controllers/ManageAromaTypeController.cs
namespace PerfumeShop.Web.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class ManageAromaTypeController : Controller
{
    private readonly IViewModelService<CatalogAromaType, ItemViewModel, CatalogDbContext> _viewModelService;

    public ManageAromaTypeController(IViewModelService<CatalogAromaType, ItemViewModel, CatalogDbContext> viewModelService)
    {
        _viewModelService = viewModelService;
    }

    [HttpGet]
    public IActionResult Index() => View();

    [HttpGet]
    public IActionResult Create() => View();

    [HttpPost]
    public async Task<IActionResult> Create(ItemViewModel obj)
    {
        if (ModelState.IsValid)
        {
            await _viewModelService.CreateModelAsync(obj);
            TempData["success"] = $"{obj.Name} was created successfully";
            return RedirectToAction(nameof(Index));
        }
        else return View(obj);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var viewModel = await _viewModelService.GetViewModelByIdAsync(id);
        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(ItemViewModel obj)
    {
        if (ModelState.IsValid)
        {
            await _viewModelService.UpdateModelAsync(obj);
            TempData["success"] = $"{obj.Name} was updated successfully";
            return RedirectToAction(nameof(Index));
        }
        return View(obj);
    }

    #region API CALLS
    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var viewModels = await _viewModelService.GetViewModelsAsync();
        return Json(new { data = viewModels });
    }

    [HttpDelete]
    public async Task<IActionResult> Delete(int id)
    {
        var viewModel = await _viewModelService.GetViewModelByIdAsync(id);

        if (viewModel is null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }

        await _viewModelService.DeleteModelAsync(viewModel);

        return Json(new { success = true, message = $"{viewModel.Name} was deleted successfully" });
    }
    #endregion
}

PerfumeShop/PerfumeShop.Web/Areas/Admin/Views/ManageAromaType/Create.cshtml
@model ItemViewModel

<form method="post" asp-controller="ManageAromaType" asp-action="Create" class="row g-3 needs-validation" novalidate>

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h2 class="text-muted">Create Aroma Type</h2>
		<div class="btn-toolbar mb-2 mb-md-0">
			<div class="text-end">

				<button type="submit" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-check-lg">Create</span>
				</button>

				<a asp-controller="ManageAromaType" asp-action="Index" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-reply"> Back</span>
				</a>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="mb-3">
			<label asp-for="@Model.Name"></label>
			<input asp-for="@Model.Name" class="form-control" required>
			<span asp-validation-for="@Model.Name" class="text-danger"></span>
			<div class="valid-feedback">
				Valid!
			</div>
		</div>
	</div>
</form>

@section Scripts{
	<partial name="_ValidationScriptsPartial" />
}

PerfumeShop/PerfumeShop.Web/Areas/Admin/Views/ManageAromaType/Edit.cshtml
@model ItemViewModel

<form method="post" asp-controller="ManageAromaType" asp-action="Edit" class="row g-3 needs-validation" novalidate>

	<input asp-for="@Model.Id" hidden />

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h2 class="text-muted">Edit Aroma Type</h2>
		<div class="btn-toolbar mb-2 mb-md-0">
			<div class="text-end">

				<button type="submit" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-check-lg">Save</span>
				</button>

				<a asp-controller="ManageAromaType" asp-action="index" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-reply"> Back</span>
				</a>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="mb-3">
			<label asp-for="@Model.Name"></label>
			<input asp-for="@Model.Name" class="form-control" required>
			<span asp-validation-for="@Model.Name" class="text-danger"></span>
			<div class="valid-feedback">
				Valid!
			</div>
		</div>
	</div>
</form>

@section Scripts{
	<partial name="_ValidationScriptsPartial" />

}

PerfumeShop/PerfumeShop.Web/Areas/Admin/Views/ManageAromaType/Index.cshtml
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2 class="text-muted">Aroma Types</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="text-end">
            <a asp-controller="ManageAromaType" asp-action="Create" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
                <span class="bi bi-pen">Add</span>
            </a>
        </div>
    </div>
</div>

<table id="aromaTypeData" class="table table-bordered table-striped table-sm">
    <thead>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
</table>

@section Scripts{
    <script src="~/js/tables/aromaType-table.js"></script>
}