PerfumeShop/PerfumeShop.Web/ViewModels/ManageProductViewModel.cs
namespace PerfumeShop.Web.ViewModels;


public sealed class ManageProductViewModel
{
    public ProductViewModel? Product { get; set; }
    public IEnumerable<SelectListItem>? Brands { get; set; }
    public IEnumerable<SelectListItem>? AromaTypes { get; set; }
    public IEnumerable<SelectListItem>? Genders { get; set; }
    public IEnumerable<SelectListItem>? ReleaseForms { get; set; }

	public ManageProductViewModel()
	{
	}

	public ManageProductViewModel(
        ProductViewModel? product,
        IEnumerable<SelectListItem>? brands,
        IEnumerable<SelectListItem>? aromaTypes,
        IEnumerable<SelectListItem>? genders,
        IEnumerable<SelectListItem>? releaseForms)
    {
        Product = product;
        Brands = brands;
        AromaTypes = aromaTypes;
        Genders = genders;
        ReleaseForms = releaseForms;      
    }
}

PerfumeShop/PerfumeShop.Web/Areas/Admin/Controllers/ManageProductController.cs
namespace PerfumeShop.Web.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class ManageProductController : Controller
{
    private readonly IContentManager _contentManager;
    private readonly IViewModelService<CatalogProduct, ProductViewModel, CatalogDbContext> _productService;
    private readonly IViewModelService<CatalogBrand, ItemViewModel, CatalogDbContext> _brandService;
    private readonly IViewModelService<CatalogGender, ItemViewModel, CatalogDbContext> _genderService;
    private readonly IViewModelService<CatalogAromaType, ItemViewModel, CatalogDbContext> _aromaTypeService;
    private readonly IViewModelService<CatalogReleaseForm, ItemViewModel, CatalogDbContext> _releaseFormService;


    public ManageProductController(
        IContentManager contentManager,
        IViewModelService<CatalogProduct, ProductViewModel, CatalogDbContext> catalogService,
        IViewModelService<CatalogBrand, ItemViewModel, CatalogDbContext> brandService,
        IViewModelService<CatalogGender, ItemViewModel, CatalogDbContext> genderService,
        IViewModelService<CatalogAromaType, ItemViewModel, CatalogDbContext> typeService,
        IViewModelService<CatalogReleaseForm, ItemViewModel, CatalogDbContext> releaseFormService)      
    {
        _contentManager = contentManager;
        _productService = catalogService;
        _brandService = brandService;
        _genderService = genderService;
        _aromaTypeService = typeService;
        _releaseFormService = releaseFormService;
    }

    [HttpGet]
    public IActionResult Index() => View();

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var brands = await _brandService.GetViewModelsAsync();
        var types = await _aromaTypeService.GetViewModelsAsync();
        var genders = await _genderService.GetViewModelsAsync();
        var releaseForms = await _releaseFormService.GetViewModelsAsync();

        ManageProductViewModel manageViewModel = new(
            new ProductViewModel(),
            brands.ToSelectListItems(),
            types.ToSelectListItems(),
            genders.ToSelectListItems(),
            releaseForms.ToSelectListItems());

        return View(manageViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ManageProductViewModel manageViewModel)
    {
        var files = HttpContext.Request.Form.Files;

        if (files.Count > 0)
        {
            _contentManager.UploadFiles(HttpContext.Request.Form.Files, Constants.CATALOG_IMAGE_PATH);
            manageViewModel.Product!.PictureUri = _contentManager.NameFiles.FirstOrDefault();
        }

        if (ModelState.IsValid)
        {
            await _productService!.CreateModelAsync(manageViewModel.Product!);

            TempData["success"] = $"{manageViewModel.Product.Name} was created successfully";

            return RedirectToAction(nameof(Index));
        }
        else return View(manageViewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var product = await _productService!.GetViewModelByIdAsync(id);
        var brands = await _brandService.GetViewModelsAsync();
        var types = await _aromaTypeService.GetViewModelsAsync();
        var genders = await _genderService.GetViewModelsAsync();
        var releaseForms = await _releaseFormService.GetViewModelsAsync();

        ManageProductViewModel manageViewModel = new(
            product,
            brands.ToSelectListItems(),
            types.ToSelectListItems(),
            genders.ToSelectListItems(),
            releaseForms.ToSelectListItems());

        return View(manageViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(ManageProductViewModel manageViewModel)
    {
        var files = HttpContext.Request.Form.Files;

        if (files.Count > 0)
        {
            _contentManager.RemoveFile(Constants.CATALOG_IMAGE_PATH, manageViewModel.Product.PictureUri);
            _contentManager.UploadFiles(files, Constants.CATALOG_IMAGE_PATH);
            manageViewModel.Product.PictureUri = _contentManager.NameFiles.FirstOrDefault();
        }

        if (ModelState.IsValid)
        {
            var viewModel = manageViewModel.Product;
            await _productService!.UpdateModelAsync(viewModel!);

            TempData["success"] = $"{manageViewModel.Product?.Name} was updated successfully";

            return RedirectToAction(nameof(Details), new { id = viewModel!.Id });
        }
        else return RedirectToAction();
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var viewModel = await _productService!.GetViewModelByIdAsync(id);
        return View(viewModel);
    }

    #region API CALLS
    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var viewModels = await _productService.GetViewModelsAsync();
        return Json(new { data = viewModels });
    }

    [HttpDelete]
    public async Task<IActionResult> Delete(int id)
    {
        var viewModel = await _productService.GetViewModelByIdAsync(id);

        if (viewModel is null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }
        _contentManager.RemoveFile(Constants.CATALOG_IMAGE_PATH, viewModel.PictureUri);

        await _productService.DeleteModelAsync(viewModel);

        return Json(new { success = true, message = $"{viewModel.Name} was deleted successfully" });
    }
    #endregion
}

PerfumeShop/PerfumeShop.Web/Areas/Admin/Views/ManageProduct/Create.cshtml
@model ManageProductViewModel

<form method="post" asp-controller="ManageProduct" asp-action="Create" enctype="multipart/form-data" class="row g-3 needs-validation" novalidate>
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h2 class="text-muted">Create Product</h2>
		<div class="btn-toolbar mb-2 mb-md-0">
			<div class="text-end">

				<button type="submit" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-check-lg">Create</span>
				</button>

				<a asp-controller="ManageProduct" asp-action="index" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-reply"> Back</span>
				</a>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="mb-3">
			<label asp-for="Product!.Name"></label>
			<input asp-for="Product!.Name" class="form-control" required>
			<span asp-validation-for="Product!.Name" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3">
			<label asp-for="Product!.Description"></label>
			<textarea asp-for="Product!.Description" id="tinytextarea" rows="3" class="form-control"
					  required placeholder="Text area must be required"></textarea>
			<span asp-validation-for="Product!.Description" class="text-danger"></span>
		</div>
		<div class="mb-3 col-4">
			<label asp-for="Product!.Price"></label>
			<div class="input-group">
				<span class="input-group-text">$</span>
				<input asp-for="Product!.Price" type="number" value="0.00"
				class="form-control" placeholder="0.00" step="0.01" min="1" max="999999" required>
			</div>
			<span asp-validation-for="Product!.Price" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-4">
			<label asp-for="Product!.Stock"></label>
			<div class="input-group">
				<span class="input-group-text">qty.</span>
				<input asp-for="Product!.Stock" placeholder="1" class="form-control" min="1" max="@int.MaxValue" required>
			</div>
			<span asp-validation-for="Product!.Stock" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-4">
			<label asp-for="Product!.Volume"></label>
			<div class="input-group">
				<span class="input-group-text">ml.</span>
				<input asp-for="Product!.Volume" placeholder="1" class="form-control" min="1" max="@int.MaxValue" required>
			</div>
			<span asp-validation-for="Product!.Volume" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.Brand"></label>
			<select asp-for="Product!.BrandId" asp-items="@Model.Brands" class="form-select" required>
				<option selected disabled value="">--Select Brand--</option>
			</select>
			<span asp-validation-for="Product!.BrandId" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.Gender"></label>
			<select asp-for="Product!.GenderId" asp-items="@Model.Genders" class="form-select" required>
				<option selected disabled value="">--Select Gender--</option>
			</select>
			<span asp-validation-for="Product!.GenderId" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.AromaType"></label>
			<select asp-for="Product!.AromaTypeId" asp-items="@Model.AromaTypes" class="form-select" required>
				<option selected disabled value="">--Select Aroma Type--</option>
			</select>
			<span asp-validation-for="Product!.AromaTypeId" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.ReleaseForm"></label>
			<select asp-for="Product!.ReleaseFormId" asp-items="@Model.ReleaseForms" class="form-select" required>
				<option selected disabled value="">--Select Release Form--</option>
			</select>
			<span asp-validation-for="Product!.ReleaseFormId" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-12">
			<div class="form-group row">
				<label asp-for="Product!.PictureUri"></label>
				<div class="col-12">
					<input type="file" name="files" id="uploadBox" class=" form-control" required />
				</div>
			</div>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
	</div>
</form>

@section Scripts{
	<script src="~/js/textareaTinyMCE.js"></script>
	<partial name="_ValidationScriptsPartial" />
}

PerfumeShop/PerfumeShop.Web/Areas/Admin/Views/ManageProduct/Details.cshtml
@model ProductViewModel

<form method="get">

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h2 class="text-muted">Detail Product</h2>
		<div class="btn-toolbar mb-2 mb-md-0">
			<div class="text-end">
				<a asp-controller="ManageProduct" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-wrench"> Edit</span>
				</a>
				<a asp-controller="ManageProduct" asp-action="index" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-reply"> Back</span>
				</a>
			</div>
		</div>
	</div>


	<div class="d-flex position-relative">
		<div class="col-md-4 px-0">
			<img src="@Constants.CATALOG_IMAGE_PATH@Model.PictureUri" class="w-75" style="max-width:350px">
		</div>
		<div class="col-md-6 p-4 ps-md-0">
			<div>
				<p><b>Name: </b>@Model.Name</p>
			</div>
			<div class="col-4">
				<p><b>Brand: </b>@Model.Brand?.Name</p>
				<p><b>Gender: </b>@Model.Gender?.Name</p>
				<p><b>Release Form: </b>@Model.ReleaseForm.Name</p>
				<p><b>Aroma Type: </b>@Model.AromaType.Name</p>
			</div>
			<div>
				<p><b>Price: </b>@Model.Price.ToString("c")</p>
				@if (Model.DiscountPrice is not null)
				{
					<p><b>Discount Price: </b>@Model.DiscountPrice?.ToString("c")</p>				
				}
				<p><b>Stock: </b>@Model.Stock</p>
				<p><b>Date Delivery: </b>@Model.DateDelivery</p>
			</div>
			<div>
				<b>Description:</b>
				<div class="small">
					<p>@Html.Raw(Model.Description)</p>
				</div>
			</div>
		</div>
	</div>

</form>

PerfumeShop/PerfumeShop.Web/Areas/Admin/Views/ManageProduct/Edit.cshtml
@model ManageProductViewModel

<form method="post" asp-controller="ManageProduct" asp-action="Edit" enctype="multipart/form-data" class="row g-3 needs-validation" novalidate>

	<input asp-for="Product!.Id" hidden />
	<input asp-for="Product!.PictureUri" hidden />

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
		<h2 class="text-muted">Edit Product</h2>
		<div class="btn-toolbar mb-2 mb-md-0">
			<div class="text-end">

				<button type="submit" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-check-lg">Save</span>
				</button>

				<a asp-controller="ManageProduct" asp-action="Details" asp-route-id="@Model.Product!.Id" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
					<span class="bi bi-reply"> Back</span>
				</a>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="mb-3">
			<label asp-for="Product!.Name"></label>
			<input asp-for="Product!.Name" class="form-control" required>
			<span asp-validation-for="Product!.Name" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3">
			<label asp-for="Product!.Description"></label>
			<textarea asp-for="Product!.Description" id="tinytextarea" rows="3" class="form-control"
					  required placeholder="Text area must be required"></textarea>
			<span asp-validation-for="Product!.Description" class="text-danger"></span>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.Price"></label>
			<div class="input-group">
				<span class="input-group-text">$</span>
				<input asp-for="Product!.Price" type="number"
					class="form-control" placeholder="0.00" step="0.01" min="1" max="999999" required>
				<span asp-validation-for="Product!.Price" class="text-danger"></span>
				<div class="valid-feedback">
					Valid
				</div>
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product.DiscountPrice"></label>
			<div class="input-group">
				<span class="input-group-text">$</span>
				<input asp-for="Product.DiscountPrice" type="number"
					   class="form-control" placeholder="0.00" step="0.01" min="0" max="999999" required>
				<span asp-validation-for="Product.DiscountPrice" class="text-danger"></span>
				<div class="valid-feedback">
					Valid
				</div>
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.Stock"></label>
			<div class="input-group">
				<span class="input-group-text">qty.</span>
				<input asp-for="Product!.Stock" placeholder="1" class="form-control" min="1" max="@int.MaxValue" required>
			</div>
			<span asp-validation-for="Product!.Stock" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.Volume"></label>
			<div class="input-group">
				<span class="input-group-text">ml.</span>
				<input asp-for="Product!.Volume" placeholder="1" class="form-control" min="1" max="@int.MaxValue" required>
			</div>
			<span asp-validation-for="Product!.Volume" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.Brand"></label>
			<select asp-for="Product!.BrandId" asp-items="@Model.Brands" class="form-select" required>
				<option selected disabled value="">--Select Brand--</option>
			</select>
			<span asp-validation-for="Product!.BrandId" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.Gender"></label>
			<select asp-for="Product!.GenderId" asp-items="@Model.Genders" class="form-select" required>
				<option selected disabled value="">--Select Gender--</option>
			</select>
			<span asp-validation-for="Product!.GenderId" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.AromaType"></label>
			<select asp-for="Product!.AromaTypeId" asp-items="@Model.AromaTypes" class="form-select" required>
				<option selected disabled value="">--Select Aroma Type--</option>
			</select>
			<span asp-validation-for="Product!.AromaTypeId" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-3">
			<label asp-for="Product!.ReleaseForm"></label>
			<select asp-for="Product!.ReleaseFormId" asp-items="@Model.ReleaseForms" class="form-select" required>
				<option selected disabled value="">--Select Release Form--</option>
			</select>
			<span asp-validation-for="Product!.ReleaseFormId" class="text-danger"></span>
			<div class="valid-feedback">
				Valid
			</div>
		</div>
		<div class="mb-3 col-12">
			<div class="form-group row">
				<span>
					New <label asp-for="@Model.Product!.PictureUri"></label>
				</span>
				<div class="mb-3">
					<input type="file" name="files" id="uploadBox" class="form-control" />
				</div>
			</div>
			<div class="mb-3 col-3">
				<div class="mb-3">
					<span>Current Picture</span>
					<img src="@Constants.CATALOG_IMAGE_PATH@Model.Product!.PictureUri"
						 style="width:100%; border-radius:10px; border:2px solid #D6D6D8" />
				</div>
			</div>
		</div>
	</div>
</form>


@section Scripts{
	<partial name="_ValidationScriptsPartial" />
	<script src="~/js/textareaTinyMCE.js"></script>
}

PerfumeShop/PerfumeShop.Web/Areas/Admin/Views/ManageProduct/Index.cshtml
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2 class="text-muted">Products</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="text-end">
            <a asp-controller="ManageProduct" asp-action="Create" class="btn btn-outline-secondary btn-sm shadow-none" style="width:80px">
                <span class="bi bi-pen">Add</span>
            </a>
        </div>
    </div>
</div>

<table id="productData" class="table table-bordered table-striped table-sm">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Discount Price</th>
            <th>Volume</th>
            <th>Stock</th>
            <th>Brand</th>
            <th>Gender</th>
            <th>Aroma Type</th>
            <th>Release Form</th>
            <th>Date Delivery</th>
            <th></th>
        </tr>
    </thead>
</table>

@section Scripts{
    <script src="~/js/tables/product-table.js"></script>
}